name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Executable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.2'
        cabal-version: '3.4'
    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Build
      run: make
    - name: Install
      run: make destdir=. install
    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: metroc-bin
        path: ./metroc
        if-no-files-found: error
    - name: Run Metro tests
      run: ./metroc test
    - name: Run examples/print.metro
      run: echo "stdout" | ./metroc run examples/print.metro
    - name: Run examples/arithmetics.metro
      run: ./metroc run --assertions examples/arithmetics.metro
    - name: Run examples/murmur3.metro
      run: ./metroc run --assertions examples/murmur3.metro
    - name: Run examples/uint.metro
      run: ./metroc run --assertions examples/uint.metro
