name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  WASMTIME_VERSION: "1.0.1"

jobs:
  build:
    name: Build Executable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: haskell/actions/setup@v2
    - uses: haskell/actions/hlint-setup@v2
    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ hashFiles('**/*.cabal') }}
        restore-keys: ${{ runner.os }}-build-
    - name: Install Wasmtime ${{ env.WASMTIME_VERSION }}
      uses: ./.github/actions/install-wasmtime
      with:
        version: ${{ env.WASMTIME_VERSION }}
    - name: Update Local Hackage Database
      run: cabal update
    - name: Build
      run: make build
    - name: Lint
      uses: haskell/actions/hlint-run@v2
      with:
        fail-on: warning
    - name: Install
      run: make destdir=. install
    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: metroc-bin
        path: ./metroc
        if-no-files-found: error
    - name: Run Metro tests
      run: ./metroc test
    - name: Run examples/print.metro
      run: echo "stdout" | ./metroc run examples/print.metro
    - name: Run examples/arithmetics.metro
      run: ./metroc run --assertions examples/arithmetics.metro
    - name: Run examples/murmur3.metro
      run: ./metroc run --assertions examples/murmur3.metro
    - name: Run examples/uint.metro
      run: ./metroc run --assertions examples/uint.metro
