name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  WASMTIME_URL: https://github.com/bytecodealliance/wasmtime/releases/download/v1.0.1/wasmtime-v1.0.1-x86_64-linux-c-api.tar.xz

jobs:
  build:
    name: Build Executable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '9.0.2'
        cabal-version: '3.4'
    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install Wasmtime 1.0.1
      run: |
        curl -L ${{ env.WASMTIME_URL }} | tar xJ
        sudo mv wasmtime-v1.0.1-x86_64-linux-c-api/lib/* /usr/lib
    - name: Build
      run: make
    - name: Lint
      run: |
        wget https://github.com/ndmitchell/hlint/releases/download/v3.3/hlint-3.3-x86_64-linux.tar.gz -O hlint.tar.gz
        tar xzf hlint.tar.gz
        ./hlint-3.3/hlint src bin metroc-wasmtime/src
    - name: Install
      run: make destdir=. install
    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: metroc-bin
        path: ./metroc
        if-no-files-found: error
    - name: Run Metro tests
      run: ./metroc test
    - name: Run examples/print.metro
      run: echo "stdout" | ./metroc run examples/print.metro
    - name: Run examples/arithmetics.metro
      run: ./metroc run --assertions examples/arithmetics.metro
    - name: Run examples/murmur3.metro
      run: ./metroc run --assertions examples/murmur3.metro
    - name: Run examples/uint.metro
      run: ./metroc run --assertions examples/uint.metro
